### ISSUE TITLE
Add a CosmosChain pre start hook 

### ISSUE THREAD

**Issue by colin-axner** [strangelove-ventures/interchaintest#418]
Add a function to the `CosmosChain` struct which does a callback before the node is started. This would allow the cosmos chain creator to implement a function which modifies any configuration parameter they would like. With this addition, the `ModifyGenesis` function could be deprecated and we could expect the genesis modifications to occur within the pre startup hook. 

The use case which motivates this proposal is having the ability to modify the app.toml file (setting the halt height) before chain startup. I will be working on my fork for this to test an e2e we are adding on ibc-go, I can open a pr with the suggested changes

I plan to add a `cosmos.ChainConfig` type which has:
```go
// existing type
type CosmosChain struct {
    ...
    chainConfig ChainConfig
    ...
}

type ChainConfig struct {
    numValidators int
    numFullNodes  int
    PreStartupHook func(node *ChainNode) 
}
```

After `SetPeers` before `StartContainer` [here](https://github.com/strangelove-ventures/interchaintest/blob/main/chain/cosmos/cosmos_chain.go#L830) add:
```go
if c.ChainConfig.PreStartupHook != nil {
    c.ChainConfig.PreStartupHook(n)
}
```

No strong preference on function naming. The numValidator/numFullNodes/ChainConfig changes can be left out if desired

**Comment by agouin** [comment]
Hi @colin-axner , this is already possible with `ConfigFileOverrides` in the chain config. https://github.com/strangelove-ventures/interchaintest/blob/4e43739472a180c802943a1594ff26e74688088d/ibc/types.go#L40

`ModifyGenesis` is also useful as it will only run once on the genesis file before distributing it out to all nodes, rather than running for all nodes.

Let me know if this does not work for your use case.

**Comment by colin-axner** [comment]
Nice that should work, thanks!
