### ISSUE TITLE
Questions and feedback from trying to use for CosmWasm IBC testing

### ISSUE THREAD

**Issue by 0xekez** [strangelove-ventures/interchaintest#424]
First of all thanks for writing this and making it open source. I'm excited about how customizable this seems.

I'm running into a couple issues trying to test a CosmWasm contract. Is there an example somewhere of doing this? The juno chain halt reproduction seems to not be in the examples/ folder and use an old version of this library, so all of the below could be completely missguided as I'm making it up as I go.

### 1. Trying to store a wasm file gives an out-of-gas error.

To reproduce, checkout [this branch](https://github.com/0xekez/cw-ibc-example/blob/zeke/strangelove/tests/strangelove/learn_ibc_test.go#L93) and run `go test ./...` from the `tests/strangelove` folder. When storing a wasm file, I get an error:

```
learn_ibc_test.go:93: transaction failed with code 11: out of gas in location: txSize; gasWanted: 200000, gasUsed: 724653: out of gas
```

I've tried bumping the gas adjustment in the chain config to 2x, and it still doesn't work. As the method has no params for gas, and this is a 192kb wasm file (small), my best guess is that this is a configuration issue in interchaintest.

### 2. Creating a channel between juno and osmosis does not work.

With this chain config:

```
	cf := interchaintest.NewBuiltinChainFactory(zaptest.NewLogger(t), []*interchaintest.ChainSpec{
		{
			Name:    "juno",
			Version: "latest",
			ChainConfig: ibc.ChainConfig{
				GasPrices:     "0.0ujuno",
				GasAdjustment: 2.0,
			},
		},
		{
			Name:    "osmosis",
			Version: "latest",
			ChainConfig: ibc.ChainConfig{
				GasPrices:     "0.0uosmo",
				GasAdjustment: 2.0,
			},
		},
	})
```

I get an error:

```
Error: error creating clients: failed to create client on dst chain{osmosis-2}: failed to send messages on chain{osmosis-2}: rpc error: code = InvalidArgument desc = Expected 1 fee denom attached, got 0: insufficient fee: invalid request
```

I've tried permuting the junod and osmosisd versions being used to some older ones to no success. This seems like something that _should work_, so I'm not sure what's going on here.

### 3. Conversion from ibc.Chain to CosmosChain is awkward.

In order to do wasm things, you need a CosmosChain. Is there an easier way to get a CosmosChain out of an `Ibc.Chain`?

```
leftCosmosChain := left.(*cosmos.CosmosChain)
```

Thanks for the help! I'm happy to add more context and you all know where to find me on Discord I believe.

**Comment by misko9** [comment]
Have you seen the ibc wasm contract example in the v3 branch? If not, I would start there (examples/ibc/wasm/wasm_ibc_test.go) and there is a built-in function StoreContract() which uses "--gas auto" for the store that should help. We added most support to the v3 branch since, at the time, wasmd was still on ibc-go v3 and we wanted the codec support. It is now on ibc-go v4 and I believe our v4 branch is also fully functional with that code. Give that a try and let me know if you still run into issue.

**Comment by 0xekez** [comment]
> @misko9 Have you seen the ibc wasm contract example in the v3 branch?

 worked first try. confirmed it works on the v4 branch as well.

one question, and one bit of feedback from getting this wired up:

1. when does one need to call `relayer.FlushPackets` and `relayer.FlushAcknowledgements`? it seems like from the tests packets are relayed automatically, is there a way to disable that so packets can be relayed (and blocked on) in the test?
2. running `CosmosChain.QueryContract` returns data from the chain in the form `{"data": QUERY}`, so for example, if a query response looks like `{"count": u32}`, what is returned is `{"data":{"count":u32}}`. This [confused me](https://github.com/0xekez/cw-ibc-example/blob/zeke/strangelove/tests/strangelove/learn_ibc_test.go#L202-L204) for a while as other CosmWasm testing libraries hide that `data` key and let you unmarshal from the `QUERY`. It might be nice to document this or make it a little more explicit in the examples.

my end goal here is to use this framework to simulate lite client expiry. do you know of any example code that might help me get started on that?

thank you for the help!

**Comment by misko9** [comment]
Good to hear! And glad things are working on the v4 branch too!

You typically shouldn't need the relayer flush commands because if you start the relayer, it will follow each block created and relay packets. If you want finer grain control of when packets are relayed, you can use the flush commands without starting the relayer.

As for the query response, great feedback. This is definitely something we should document in the near term and possibly just abstract away to be similar to other CosmWasm testing libraries.

I'm not aware of any light client expiry test cases. The cosmos/ibc-go repo has a lot of great test cases being built out in their e2e dir, but I don't see one for that. You can try turning down the trust period of the chain to a minute or two and see if that works. Just be sure to stop the relayer for at least as long as the trust period so the light client can expire, otherwise the relayer is supposed to automatically update the client state if it is nearing the trust period without an update state being seen.

**Comment by 0xekez** [comment]
OK! got this working!

https://github.com/0xekez/cw-ibc-example/blob/main/tests/strangelove/light_client_expiry_test.go

thank you for the help @misko9
