### ISSUE TITLE
default chainIDs do not have revision number

### ISSUE THREAD

**Issue by charleenfei** [strangelove-ventures/interchaintest#768]
i noticed while writing [this e2e for our feature migration](https://github.com/cosmos/ibc-go/pull/4623/files#diff-1ae1a8377cd14a2933deeac1653c47964d72be06269a0c3f8dd9a7d97a868bcaR99) from govv1beta1 to govv1 that the default chainIDs created by interchaintest do not conform to the default revision number format.

i think this could potentially cause unexpected issues, as having a non conformant chain ID means a chain will not be able to access misbehaviour support. it might be nice to have the default chainID have a conformant chainID with revision number, maybe with custom opt to then create non-revision chain IDs, rather than the other way around.

**Comment by Reecepbcups** [comment]
@charleenfei I had a look and this _may_ be due to how ibc-go e2e testsuite is [setup here for chain-a and chain-b](https://github.com/cosmos/ibc-go/blob/charly/issue%234599-add-proposal-simulations-for-msgrecoverclient-and-msgibcsoftwareupgrade/e2e/testsuite/testconfig.go#L110-L123). Can you confirm if this is the case?

I assume those should return chain-1 and chain-2 to fit your use case and conform the to the standard correct? if not please let me know

**Comment by charleenfei** [comment]
aha, i will definitely check this out, thank you!
